Importing local dependencies

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split

In [2]:
concrete_dataset=pd.read_csv("concrete_data.csv")

In [3]:
concrete_dataset

cement  blast_furnace_slag  fly_ash  water  superplasticizer  \
0      540.0                 0.0      0.0  162.0               2.5   
1      540.0                 0.0      0.0  162.0               2.5   
2      332.5               142.5      0.0  228.0               0.0   
3      332.5               142.5      0.0  228.0               0.0   
4      198.6               132.4      0.0  192.0               0.0   
...      ...                 ...      ...    ...               ...   
1025   276.4               116.0     90.3  179.6               8.9   
1026   322.2                 0.0    115.6  196.0              10.4   
1027   148.5               139.4    108.6  192.7               6.1   
1028   159.1               186.7      0.0  175.6              11.3   
1029   260.9               100.5     78.3  200.6               8.6   

      coarse_aggregate  fine_aggregate   age  concrete_compressive_strength  
0               1040.0            676.0   28                          79.99  
1               1055.0            676.0   28                          61.89  
2                932.0            594.0  270                          40.27  
3                932.0            594.0  365                          41.05  
4                978.4            825.5  360                          44.30  
...                ...              ...  ...                            ...  
1025             870.1            768.3   28                          44.28  
1026             817.9            813.4   28                          31.18  
1027             892.4            780.0   28                          23.70  
1028             989.6            788.9   28                          32.77  
1029             864.5            761.5   28                          32.40  

[1030 rows x 9 columns]

In [4]:
concrete_dataset.describe()

cement  blast_furnace_slag      fly_ash        water  \
count  1030.000000         1030.000000  1030.000000  1030.000000   
mean    281.167864           73.895825    54.188350   181.567282   
std     104.506364           86.279342    63.997004    21.354219   
min     102.000000            0.000000     0.000000   121.800000   
25%     192.375000            0.000000     0.000000   164.900000   
50%     272.900000           22.000000     0.000000   185.000000   
75%     350.000000          142.950000   118.300000   192.000000   
max     540.000000          359.400000   200.100000   247.000000   

       superplasticizer  coarse_aggregate  fine_aggregate           age  \
count       1030.000000       1030.000000      1030.000000  1030.000000   
mean           6.204660        972.918932       773.580485    45.662136   
std            5.973841         77.753954        80.175980    63.169912   
min            0.000000        801.000000       594.000000     1.000000   
25%            0.000000        932.000000       730.950000     7.000000   
50%            6.400000        968.000000       779.500000    28.000000   
75%           10.200000       1029.400000       824.000000    56.000000   
max           32.200000       1145.000000       992.600000   365.000000   

       concrete_compressive_strength  
count                    1030.000000  
mean                       35.817961  
std                        16.705742  
min                         2.330000  
25%                        23.710000  
50%                        34.445000  
75%                        46.135000  
max                        82.600000

In [5]:
concrete_dataset.isnull().sum()

cement                           0
blast_furnace_slag               0
fly_ash                          0
water                            0
superplasticizer                 0
coarse_aggregate                 0
fine_aggregate                   0
age                              0
concrete_compressive_strength    0
dtype: int64

In [6]:
x=concrete_dataset.drop(columns="concrete_compressive_strength",axis=1)

In [7]:
x

cement  blast_furnace_slag  fly_ash  water  superplasticizer  \
0      540.0                 0.0      0.0  162.0               2.5   
1      540.0                 0.0      0.0  162.0               2.5   
2      332.5               142.5      0.0  228.0               0.0   
3      332.5               142.5      0.0  228.0               0.0   
4      198.6               132.4      0.0  192.0               0.0   
...      ...                 ...      ...    ...               ...   
1025   276.4               116.0     90.3  179.6               8.9   
1026   322.2                 0.0    115.6  196.0              10.4   
1027   148.5               139.4    108.6  192.7               6.1   
1028   159.1               186.7      0.0  175.6              11.3   
1029   260.9               100.5     78.3  200.6               8.6   

      coarse_aggregate  fine_aggregate   age  
0               1040.0            676.0   28  
1               1055.0            676.0   28  
2                932.0            594.0  270  
3                932.0            594.0  365  
4                978.4            825.5  360  
...                ...              ...  ...  
1025             870.1            768.3   28  
1026             817.9            813.4   28  
1027             892.4            780.0   28  
1028             989.6            788.9   28  
1029             864.5            761.5   28  

[1030 rows x 8 columns]

In [8]:
y=concrete_dataset["concrete_compressive_strength"]

In [9]:
y

0       79.99
1       61.89
2       40.27
3       41.05
4       44.30
        ...  
1025    44.28
1026    31.18
1027    23.70
1028    32.77
1029    32.40
Name: concrete_compressive_strength, Length: 1030, dtype: float64

Correlations:/
positive Correlations:/
negative Correlations:/

In [10]:
# Correlations=concrete_dataset.corr()

In [11]:
# plt.figure(figsize=(10,10))
# sns.heatmap(Correlations, cbar= True , square= True, fmt="0.1f",annot=True,annot_kws={"size":8},cmap="blues")

splitting the data by train test split

In [12]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=2)

Training the model:/


In [13]:
model=XGBRegressor()

In [14]:
model.fit(x_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [15]:
x_train_prediction=model.predict(x_train)

In [16]:
x_train_prediction

array([68.619865 , 38.224728 , 42.9525   , 38.363163 , 65.17686  ,
       39.439487 , 32.64333  , 22.48393  , 10.829868 , 33.534283 ,
       37.807453 , 39.27386  , 55.451897 , 42.12537  , 33.0291   ,
       15.48698  , 79.39726  ,  3.3884516, 20.548979 , 25.928717 ,
       21.285604 , 31.816593 , 13.546004 , 12.18756  , 15.302359 ,
       24.485193 , 42.600845 , 32.63002  , 15.554774 , 77.29553  ,
       35.211216 , 27.671175 , 52.987926 , 23.566666 , 39.524994 ,
       34.97404  , 40.430218 , 14.386654 , 22.786339 , 56.627464 ,
       28.984272 , 55.092525 , 66.22548  , 10.033386 , 40.56081  ,
       33.328953 , 44.760635 , 12.379601 , 25.944841 , 15.035413 ,
       41.987144 , 19.174997 , 26.539547 ,  8.090269 , 29.698572 ,
       13.353449 , 39.750496 , 40.888145 , 37.575516 , 43.259792 ,
       32.98587  , 50.01843  , 54.11142  , 39.69437  , 22.911034 ,
       31.890652 , 33.534283 , 24.488966 , 33.385876 , 31.410841 ,
       55.210896 , 38.581165 , 12.32166  , 36.27243  , 40.4148

In [17]:
#R Square Error 
err1=metrics.r2_score(y_train,x_train_prediction)

In [18]:
err1

0.9951271934408594

In [19]:
#Mean square error 

In [20]:
err2=metrics.mean_squared_error(y_train,x_train_prediction)

In [21]:
err2

1.3980154420498476

Testing Data Prediction

In [22]:
x_test_prediction=model.predict(x_test)

In [23]:
x_test_prediction

array([40.662773 , 16.653461 , 21.16065  , 14.991272 , 39.007275 ,
       47.839314 , 31.518084 , 29.42882  , 25.947609 ,  4.1551337,
       27.567022 , 25.191795 , 46.83447  , 38.320076 , 42.603798 ,
       46.83447  , 23.121775 , 32.884895 , 60.76202  , 35.12252  ,
       24.215685 , 31.624859 , 28.327316 ,  3.1235847, 44.140465 ,
       26.98262  , 49.443615 , 37.079098 , 14.34446  , 30.015654 ,
       54.629395 , 23.223015 , 24.613642 , 27.271305 , 57.853516 ,
       30.836332 , 40.621235 , 15.966143 , 44.549957 , 31.449255 ,
       45.25119  , 39.2058   , 24.820698 , 37.34412  , 46.75582  ,
       39.770916 , 36.945145 , 18.585955 , 53.000435 , 31.058578 ,
       16.175508 , 23.422451 , 65.17686  , 64.40276  , 27.150467 ,
       42.630253 , 14.864527 , 47.76199  , 41.241314 , 39.254517 ,
       70.708954 , 46.253613 , 31.806644 , 27.652336 , 41.6156   ,
        9.020124 , 21.664919 , 49.967957 , 79.39726  , 15.0485735,
       27.247663 , 30.61431  , 46.129383 , 51.901085 , 49.4053

In [24]:
#R squared Error:/
err3=metrics.r2_score(x_test_prediction,y_test)

In [25]:
err3

0.9100018490023113

In [26]:
#Mean squared error:/

In [27]:
err4=metrics.mean_squared_error(x_test_prediction,y_test)

In [28]:
err4

22.315311835625465

In [29]:
input_data=(540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28)

In [30]:
input_data=np.asarray(input_data)

In [31]:
input_data

array([ 540. ,    0. ,    0. ,  162. ,    2.5, 1040. ,  676. ,   28. ])

In [32]:
input_data=input_data.reshape(1,-1)

In [33]:
input_data

array([[ 540. ,    0. ,    0. ,  162. ,    2.5, 1040. ,  676. ,   28. ]])

In [34]:
pred=model.predict(input_data)

In [35]:
x_train_prediction.shape()

TypeError: 'tuple' object is not callable

In [36]:
pred

array([79.871605], dtype=float32)